version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  dev-network:
    driver: bridge
